### PR TITLE
Ads prod to master branch

### PR DESCRIPTION
**Pull request by husobee**
:)

### CODE REVIEW

**Comment by v-kat** [comment]
I'd love to get https://github.com/brave-intl/challenge-bypass-ristretto/pull/32 looked at too. I got a working Dockerfile (not including m1) that I could add into this too after the whole dependency chain.

**Comment by v-kat** [comment]
Also still M1 woes.

```
 => [rust_builder 6/7] RUN git checkout 1.0.0-pre.1                                                                           0.4s
 => ERROR [rust_builder 7/7] RUN cargo build --target=x86_64-unknown-linux-musl --features nightly --release                105.2s
------
 > [rust_builder 7/7] RUN cargo build --target=x86_64-unknown-linux-musl --features nightly --release:
#0 0.497     Updating crates.io index
#0 92.55  Downloading crates ...
#0 93.17   Downloaded hmac v0.7.0
#0 93.21   Downloaded challenge-bypass-ristretto v1.0.0-pre.0
#0 93.26   Downloaded rand v0.6.4
#0 93.29   Downloaded base64 v0.9.3
#0 93.30   Downloaded sha2 v0.8.0
#0 93.36   Downloaded digest v0.8.0
#0 93.37   Downloaded crypto-mac v0.7.0
#0 93.48   Downloaded rand_pcg v0.1.1
#0 93.58   Downloaded libc v0.2.46
#0 93.68   Downloaded rand_xorshift v0.1.1
#0 93.69   Downloaded rand_core v0.3.0
#0 93.83   Downloaded rand_isaac v0.1.1
#0 93.84   Downloaded rand_chacha v0.1.1
#0 93.95   Downloaded autocfg v0.1.1
#0 93.96   Downloaded clear_on_drop v0.2.3
#0 94.14   Downloaded rand_os v0.1.1
#0 94.16   Downloaded curve25519-dalek v1.0.1
#0 94.24   Downloaded fake-simd v0.1.2
#0 94.24   Downloaded subtle v1.0.0
#0 94.41   Downloaded opaque-debug v0.2.1
#0 94.41   Downloaded block-buffer v0.7.0
#0 94.55   Downloaded safemem v0.3.0
#0 94.56   Downloaded byteorder v1.2.7
#0 94.67   Downloaded rand_hc v0.1.0
#0 94.79   Downloaded rustc_version v0.2.3
#0 94.81   Downloaded generic-array v0.12.0
#0 94.84   Downloaded subtle v2.0.0
#0 94.92   Downloaded block-padding v0.1.2
#0 95.06   Downloaded cc v1.0.28
#0 95.08   Downloaded typenum v1.10.0
#0 95.13   Downloaded semver v0.9.0
#0 95.20   Downloaded byte-tools v0.3.0
#0 95.32   Downloaded semver-parser v0.7.0
#0 95.42    Compiling semver-parser v0.7.0
#0 95.42    Compiling typenum v1.10.0
#0 95.43    Compiling libc v0.2.46
#0 95.43    Compiling autocfg v0.1.1
#0 95.43    Compiling cc v1.0.28
#0 95.43    Compiling rand_core v0.3.0
#0 99.33 thread 'main' panicked at 'assertion failed: self.bccx.region_scope_tree.scopes_intersect(old_loan.kill_scope,
#0 99.33                                              new_loan.kill_scope)', librustc_borrowck/borrowck/check_loans.rs:503:9
#0 99.33 note: Run with `RUST_BACKTRACE=1` for a backtrace.
#0 99.37
#0 99.37 error: internal compiler error: unexpected panic
#0 99.37
#0 99.37 note: the compiler unexpectedly panicked. this is a bug.
#0 99.37
#0 99.38 note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
#0 99.38
#0 99.38 note: rustc 1.32.0-nightly (25a42b2ce 2018-11-07) running on x86_64-unknown-linux-gnu
#0 99.38
#0 99.38 note: compiler flags: -C opt-level=3 --crate-type lib
#0 99.38
#0 99.38 note: some of the compiler flags provided by cargo are hidden
#0 99.38
#0 99.39 error: Could not compile `cc`.
#0 99.39 warning: build failed, waiting for other jobs to finish...
#0 105.0 error: build failed
------
failed to solve: executor failed running [/bin/sh -c cargo build --target=x86_64-unknown-linux-musl --features nightly --release]: exit code: 101
make: *** [docker-dev] Error 17
```

**Comment by v-kat** [comment]
I might also wanna update the cargo deps in git@github.com:v-kat/challenge-bypass-ristretto-ffi.git after a new version of https://crates.io/crates/challenge-bypass-ristretto/versions gets pushed then update the Dockerfile (it should work on intel but still not M1 😭 ).

**Comment by v-kat** [comment]
@Sneagan are there any special non-default kafka topic configs and/or other configs that are or will be needed for this? (we want to test on dev and I have no clue)

**Comment by evq** [comment]
Infra is all in place, plan is to do this upgrade today

**Review by Sneagan — APPROVED** [review]
Very exciting

**Pull request merged**
